### ISSUE TITLE
Не осилил установку :) Class 'Russsiq\Assistant\Support\Facades\Installer' not found

### ISSUE THREAD

**Issue by megaket4up** [russsiq/bixbite#1]
Делал все по инструкции из файла ридми, прошел в папку с сайтами valet (https://laravel.com/docs/6.x/valet), выполнил 
```
megaket4up@megaket4up Sites % composer create-project russsiq/bixbite bixbite -s dev
```
композер создал проект, подтянул зависимости, набрал в браузере http://bixbite.local, следовал всем шагам установки, ввел данные бд, миграции выполнились, сиды отработали и вот на этом шаге установка остановилась.

![изображение](https://user-images.githubusercontent.com/1254277/74098313-9cd9e980-4b38-11ea-8912-d74c55f412c0.png)

Куда смотреть и что делать? Ларавелевские логи не создались, так бы их приложил 

```
megaket4up@megaket4up Sites % uname -a
Darwin megaket4up.local 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64
```
```
megaket4up@megaket4up Sites % php -v
PHP 7.3.6 (cli) (built: Jun 17 2019 08:40:34) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.6, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.6, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.7.0, Copyright (c) 2002-2019, by Derick Rethans
```
```
megaket4up@megaket4up Sites % composer -V
Composer version 1.8.4 2019-02-11 10:52:10
```

**Comment by megaket4up** [comment]
Возможно package discovery не отработал должным образом
```
megaket4up@megaket4up bixbite % php artisan tinker
Psy Shell v0.9.12 (PHP 7.3.6 — cli) by Justin Hileman
>>> class_exists('Russsiq\\Assistant\\Facades\\Installer::class');
=> false
>>> 
```
хотя при попытке сделать
```
megaket4up@megaket4up bixbite % composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --no-ansi
Discovered Package: barryvdh/laravel-debugbar
Discovered Package: facade/ignition
Discovered Package: fideloper/proxy
Discovered Package: laravel/tinker
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: russsiq/laravel-assistant
Discovered Package: russsiq/laravel-env-manager
Discovered Package: russsiq/laravel-grecaptcha
Package manifest generated successfully.
```
по факту, пакет композером скачен, на диске он есть
<img width="1021" alt="изображение" src="https://user-images.githubusercontent.com/1254277/74098484-787f0c80-4b3a-11ea-9aa6-f5efd7101772.png">

**Comment by megaket4up** [comment]
установил только тогда, когда заменил в пакете ассистента установки вызовы фасада инсталлер на резолв в тру кач и аналогично в бефорИсталл
```
            // Выполняем копирование необходимх директорий.
            $installer = app('laravel-installer');            
            $installer->copyDirectories();

            // Создаем ссылки на необходимые директории.
            $installer->createSymbolicLinks();

            $response = $installer->beforeInstalled($request);
```

в итоге я не осилил войти в админпанель

**Comment by russsiq** [comment]
Пространство имен было неверно указано в файле **app\Services\Assistant\BeforeInstalled.php**


Было так:
```
use Russsiq\Assistant\Support\Facades\Installer;
```

Сейчас просто так:
```
use Installer;
```

Сейчас подправлено https://github.com/russsiq/bixbite/releases/tag/0.1.1

---------------

Что же касается **valet**, то с ним к сожалению не работал и даже предположить не могу, с какими сложностями можно там столкнуться.

---------------

Файл **readme** обязательно нужно прочесть. Там описан такие моменты, что после установки необходимо перейти в настройки системы, а также в настройки каждого из "модулей", а также выполнить комплексную оптимизацию.

Если этого не сделать, то в админке не будет пускать на редактирование записей.

**Comment by russsiq** [comment]
Что же касается **valet**, то с ним к сожалению не работал и даже предположить не могу, с какими сложностями можно там столкнуться.

**Comment by russsiq** [comment]
Файл readme обязательно нужно прочесть. Там описан такие моменты, что после установки необходимо перейти в настройки системы, а также в настройки каждого из "модулей", а также выполнить комплексную оптимизацию.

Если этого не сделать, то в админке не будет пускать на редактирование записей.

**Comment by irbees2008** [comment]
ну вот , опять перезаливать , тоже самое Class 'Russsiq\Assistant\Support\Facades\Installer' not found

**Comment by russsiq** [comment]
irbees2008, в данный момент эта ошибка исправлена. Перезаливать всё не надо, можете подправить только одну строку, описано в комментарии выше.

Или, возможно вы о другой ситуации упоминаете? Локально устанавливаете или на хостинг: на закэшировался ли файл в системе?
