### ISSUE TITLE
.htaccess

### ISSUE THREAD

**Issue by irbees2008** [russsiq/bixbite#2]
Установка прошла нормально, выкинуло на сайт , стили и скрипты не подключились, удалил  файл .htaccess /resources/themes/default/public , далее авторизовался на сайте и жму в админку , выкидывает http://bixi.site.ru/bixi.site.ru/panel/login , вот так, посмотрел тоже стили и скрипты не подключились удалил файл .htaccess /resources/skins/default/public , стили и скрипты появились.

**Comment by irbees2008** [comment]
где конфигурацию почистить, заново установить попробывать

**Comment by russsiq** [comment]
Удалить корневой файл `.env` - так система будет считаться не установленной.

А также, если вы самостоятельно настраиваете файлы `.htaccess`, то не забывайте ограничивать прямой доступ к таким файлам как **.php**, **.env** и т.д.

**Comment by russsiq** [comment]
А конфигурацию хостинга не добавите к вопросу?

**Comment by irbees2008** [comment]
Если есть желание посмотри где то здесь https://gigahost.dk/ru/

**Comment by irbees2008** [comment]
php 7.3 ,но при установке крестик стоит

**Comment by russsiq** [comment]
@irbees2008, ну вот я и думаю, вернуть как оно есть во фреймфорке по умолчанию, что корневая директория входящих запросов - [public](https://github.com/laravel/laravel/tree/master/public) и уже при активации темы, подтягивать в эту папку необходимые файлы.

Сделать это, чтобы больше не спотыкаться в наших расхождениях с Apache.

**Comment by irbees2008** [comment]
На сайте авторизуется, а в админку вот так получается http://bixi.site.ru/bixi.site.ru/panel/login, пробывал авторизоваться , 404.

**Comment by irbees2008** [comment]
Зашел ,по этому адресу ,что довольно  странно

**Comment by irbees2008** [comment]
Все ссылки в админке такого типа http://bixi.site.ru/bixi.site.ru/panel/articles

**Comment by irbees2008** [comment]
редактировать записи не могу, просто чистая страница

**Comment by russsiq** [comment]
В списке всех записей в панели, нужно перейти в настройки (это посередине между категориями и доп.полями) и хотя бы сохранить настройки.

**Comment by irbees2008** [comment]
Сохранил ,заработало. Это как убрать `{
  "id": 56,
  "img": null,
  "user_id": 51,
  "image_id": null,
  "state": "unpublished",
  "title": "Черновик",
  "slug": "chernovik",
  "teaser": null,
  "content": "",
  "description": null,
  "keywords": null,
  "robots": null,
  "on_mainpage": 0,
  "is_favorite": 0,
  "is_pinned": 0,
  "is_catpinned": 0,
  "allow_com": 2,
  "shares": 0,
  "views": 0,
  "votes": null,
  "rating": null,
  "created_at": "2020-02-10 15:56:41",
  "updated_at": null,`

**Comment by russsiq** [comment]
Эта отладочная информация будет выводится, пока не будет отлажен механизм с атачем и шорткодом изображений и файлов.

**Comment by russsiq** [comment]
https://github.com/russsiq/bixbite/commit/559011ab680d5caec180578718f10ff9ea260e1d
