### ISSUE TITLE
Не работает редактирование article

### ISSUE THREAD

**Issue by megaket4up** [russsiq/bixbite#3]
Установил с заполнением тестовых записей. На странице редактирования article ничего не выводит, в консоль сипит вот это
![image](https://user-images.githubusercontent.com/1254277/74408935-762cf300-4e57-11ea-863e-5d9a4dccf914.png)

**Comment by russsiq** [comment]
Необходимо перейти в настройки записей /panel/articles/settings и хотя бы просто их сохранить. Но обязательно задам стандартное поведение.
